feat: 로그인,회원가입
f-lab-edu/Cafe-in pull request #16
Opened 2023-04-01 08:23 UTC by choimiyoung

#기능
-LoginCheckAspect 이용하여 로그인 체크 여부 확인

WithdrawalCheckAspect 회원 가입 시 이미 존재하는 회원인지 확인
withdrawnAt 값을 확인하여 회원 탈퇴 일자 3일이 지났을 때 재 가입 가능
-CurrentUserIdResolver 컨트롤러 메서드에서 세션 값 바인딩
-PasswordEncrypt 패스워드 해싱 , 암호화 처리

구현 및 test코드 작성 완료 

Close #14

2023-04-02 11:38 UTC, f-lab-joseph requested changes
공백, 정렬, 인덴트 레벨 등의 기본적인 사안은 인텔리제이 자동정렬 기능을 사용해서 정리한 이후 올려주시면 좋을 것 같습니다.

2023-04-02 11:38 UTC, f-lab-joseph commented on build.gradle
> +    implementation 'org.mindrot:jbcrypt:0.4'
spring 관련 모듈만 갖고는 사용이 불가능한걸까요 ?

2023-04-02 11:38 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/aop/WithdrawalCheckAspect.java
> +
과한공백. 이런 린트오류는 인텔리제이 설정으로 자동으로 정렬/린트 하고 올려주시면 좋을 것 같습니다.

2023-04-02 11:38 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/config/WebConfig.java
> +    //DI
필요하지 않은 주석

2023-04-02 11:38 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/model/domain/Grade.java
> +
과한공백

2023-04-02 11:38 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/model/dto/request/LoginReq.java
> +
과한공백

2023-04-04 06:04 UTC, choimiyoung commented on build.gradle
> +    implementation 'org.mindrot:jbcrypt:0.4'
넵 ! 확인했습니다.

2023-04-04 06:06 UTC, choimiyoung commented on src/main/java/kr/cafeIn/cafeorder/aop/WithdrawalCheckAspect.java
> +
넵! 확인했습니다. 기본적으로 공백, 린트오류 같은 것을 더 신경써서 올리겠습니다.

2023-04-23 13:08 UTC, closed without merging