feat: 환경설정 변경 및 로그인, 로그아웃, 패스워드 변경, 회원가입 구현
f-lab-edu/Cafe-in pull request #21
Opened 2023-04-23 12:53 UTC by choimiyoung

#14 #16
#기능

> MyBatisConfig: 설정 변경 
annotation
---CurrentUserId: 로그인시 UserId를 받아올 어노테이션
---LoginCheck: 로그인 검증 
---WithdrawalCheck: 회원가입시 탈퇴 후 3일 지났는지 검증 
aop
--- LoginCheckAspect: LoginCheck 어노테이션을 이용하여 카페 자리 예약 시 로그인 체크 여부 확인 
---WithdrawalCheckAspect: WithdrawalCheck 어노테이션을 이용하여 재가입 회원 중 3일이 지났는지 체크 
config
---webConfig: CurrentUserIdResolver 추가를 위한 설정
controller
---UserController : 회원 가입/로그인/로그아웃/회원 탈퇴/ 비밀번호 변경 시  OPT 전송 /비밀번호 변경 
exception
----사용자 이용 시 발생할 수 있는 에러 RuntimeException 던져서 에러메세지 출력 
ext
---EmailSender: SMTP 설정 
mapper
---UserMapper: user 인터페이스
---OptHistoryMapper: opt 인터페이스 

domain : User,OptHistory 
dto
--request
--- LoginForgotRep: 로그인 정보 분실 dto
--- LoginReq :로그인 입력 정보  dto
--- PasswordResetReq: 패스워드 변경 dto
---SignUpReq: 회원 가입 dto

--response
--- WithdrawnReq:  회원 탈퇴  dto
service
--UserService : 사용자 서비스
--OtpService: Otp 전송 및  인증과  유효성 검증 

utils
---CurrentUserIdResolver: CurrentUserId 어노테이션이 있을 경우 세션정보를    메서드 파라미터에 바인딩 처리 
---PasswordEncrypt: bcrypt 를 이용한 패스워드 암호화 
---SessionManager: userid 를 참조하여 세션을 만든 후 저장 및 제거,  반환 

#테스트 코드

UserServiceTest : 사용자에 대한 테스트 코드
CafeorderApplicationTests: UserService에 대한 통합 테스트 
OptServiceTest: Otp 전송 및  유효성 테스트 
JunitTest: 실제 Otp 전송 테스트 

Close #14 #16

2023-04-25 10:53 UTC, choimiyoung commented
머지 합니다

2023-04-25 10:54 UTC, f-lab-joseph requested changes
PR 이전에 lint, 코드정리는 기본입니다. 
이 부분을 항상 더 신경써주세요.

2023-04-25 10:54 UTC, f-lab-joseph commented on build.gradle
> +    /*implementation 'com.warrenstrange:google-authenticator-core:1.0.4'*/
쓸데없는 주석이면 지워주세요

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/aop/WithdrawalCheckAspect.java
> +      } else {
if 문의 중첩을 줄여주세요. 
guard clause style 에 대해 검색해보세요.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/config/WebConfig.java
> +  //DI
이 주석은 왜필요한가요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/controller/UserController.java
> + * @RestController 는 @Controller 는 view 페이지를 반환하는데 ResetAPI 를 개발하는 상황에서는 @ResponseBody 를 붙여서 데이터를
이 주석은 왜필요한가요 ? 
위의 User Controller 도 동일합니다.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/controller/UserController.java
> +  public String createForm() {
이건 왜 필요한가요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/controller/UserController.java
> +
개행이 왜 더 많나요 ? 

개행의 스타일들을 맞춰주세요.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/controller/UserController.java
> +    log.info(" id: {}",  id);
request 별로 다 로그를 남기려고 한다면 그냥 모든 request 앞단에서 로깅을 하는 방법이 더 편하지 않을까요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/controller/UserController.java
> +    log.info("hamham : {}",loginForgotReq);
hamham 은 뭔가요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/exception/InvalidRequestException.java
> +public class InvalidRequestException extends RuntimeException {
이름을 봤을땐 주석의 설명보다 더 일반적으로 사용되는 익셉션같은데 어느 설명이 맞는건가요  ?
주석의 설명이 맞다면 이름을 더 구체화해주세요.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/ext/EmailSender.java
> +        return new PasswordAuthentication("gksrlfaldud@gmail.com", "qsioeyftboaujdls");
아이디 패스워드가 public github 에 노출되면 안됩니다. 수정해주세요.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/LoginService.java
> +    if (PasswordEncrypt.isMatch(loginReq.getPassword(), user.get().getPassword())) {
Optional 처리에 대해서 리뷰드렸는데 반영이 안된 것 같습니다. PR 내용을 한번 리뷰해보셔야 할 것 같아요

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/LoginService.java
> +      throw new IllegalArgumentException("비밀번호가 유효하지 않습니다");
guard cluase

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +      // TODO
이렇게 exception 을 로그 없이 단순히 처리하는 것은 하지 않으시는게 좋겠습니다.
exception 을 처리하는 로직에서는 로그를 항상 남겨주세요. info, warn, error 어떤거든요.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +
개행이 어떤 규칙에 의해서 되고있나요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +    //opt 생성
이 주석이 왜 필요한가요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +    Long userid=user.getId();
lint.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +    OtpHistory otpHistory = new OtpHistory(userid,otp,otpExpireTime);
코드 정리 단축키 사용하시고 PR 올리신게 맞죠 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +      throw new IllegalArgumentException(); // TODO
TODO 는 어떤 이유로 있는건가요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +      throw new IllegalArgumentException(); // TODO
그리고 위에서 이미 orElseThrow 로 받았는데 isEmpty 체크는 왜 있는건가요 ?

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/OtpService.java
> +    log.info("userid:{}",userid,"newPassword:{}",newPassword);
로그 처리가 잘못됐습니다.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/UserService.java
> +   userMapper.save(user);//통과시 저장
lint

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/UserService.java
> +   LocalDateTime withdrawnAt =LocalDateTime.now();
lint

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/UserService.java
> +    }else{
lint

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/UserService.java
> +    if(existingUser.get().getWithdrawnAt().plusDays(3).isAfter(LocalDateTime.now())){
lint

2023-04-25 10:54 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/UserService.java
> +    log.info("userid:{}",userid,"newPassword:{}",newPassword);
로그 오류

2023-04-25 10:54 UTC, f-lab-joseph commented on src/test/java/kr/cafeIn/cafeorder/JunitTest.java
> +        return new PasswordAuthentication("gksrlfaldud@gmail.com", "qsioeyftboaujdls");
아이디 패스워드 제거

2023-04-25 10:54 UTC, f-lab-joseph commented on src/test/java/kr/cafeIn/cafeorder/UserServiceTest.java
> +    userService = new UserService(
TODO 를 처리하던, 필요없는 테스트라면 지우던 하는게 좋겠습니다.

2023-04-25 10:54 UTC, f-lab-joseph commented on src/test/java/kr/cafeIn/cafeorder/service/OtpServiceTest.java
> +    otpService = new OtpService(googleAuthenticator,otpHistoryMapper,userService,emailSender);
lint

2023-04-25 10:54 UTC, f-lab-joseph commented on src/test/java/kr/cafeIn/cafeorder/service/OtpServiceTest.java
> +  private GoogleAuthenticator googleAuthenticator ;
lint

2023-04-25 12:41 UTC, choimiyoung commented
확인했습니다 !

2023-04-26 17:11 UTC, f-lab-joseph requested changes

2023-04-26 17:11 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/ext/EmailSender.java
> +        return new PasswordAuthentication("gksrlfaldud@gmail.com", "qsioeyftboaujdls");
이거 중요합니다. 미노출 처리 해주세요. ~!

2023-04-26 17:11 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/mapper/UserMapper.java
> +
개행..

2023-04-26 17:11 UTC, f-lab-joseph commented on src/main/resources/mapper/UserMapper.xml
> +  <update id="updateWithdrawnAt"    >
공백은 왜있는건가요 ?

2023-04-29 14:05 UTC, f-lab-joseph requested changes

2023-04-29 14:05 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/ext/EmailSender.java
> +        return new PasswordAuthentication("", "");
공백이 아니고 설정에서 받아오는 값이 되어야겠죠 ?

2023-04-30 09:20 UTC, choimiyoung commented on src/main/java/kr/cafeIn/cafeorder/ext/EmailSender.java
> +        return new PasswordAuthentication("", "");
application.properties 에
username, password 옵션 추가 하였습니다 .

2023-05-01 04:54 UTC, f-lab-joseph commented on src/test/java/kr/cafeIn/cafeorder/JunitTest.java
> +        return new PasswordAuthentication("gksrlfaldud@gmail.com", "qsioeyftboaujdls");
이거는 제거 안하시나요 ?

2023-05-01 04:57 UTC, f-lab-joseph commented on src/main/resources/mapper/UserMapper.xml
> +    where id = #{id}
updated_at 은 업데이트 안해도 되는건가요 ? 
아래도 동일합니다.
스키마에 반영이 돼있더라도 쿼리에서도 반영을 해주는게 좋을 것 같습니다.

2023-05-01 04:58 UTC, f-lab-joseph approved these changes

2023-05-02 03:43 UTC, merged

2023-05-02 03:44 UTC, choimiyoung commented on src/main/resources/mapper/UserMapper.xml
> +    where id = #{id}
넵 확인했습니다