cafe, Menu, Table CRUD 수정
f-lab-edu/Cafe-in pull request #27
Opened 2023-05-14 11:28 UTC by shineMeoseuk

#기능

CafeController 기능 변경.
Cafe, Menu, CafeTable 기존 내용 변경.

Close #26

2023-05-17 13:36 UTC, f-lab-joseph requested changes

2023-05-17 13:36 UTC, f-lab-joseph commented on src/main/java/kr/cafeIn/cafeorder/service/CafeTableService.java
> +		if (orderMapper.isExistsNowOrderByCafeTableId(cafeTableId)) {
온라인 리뷰때 말씀드렸지만 잘못된 코드로 보입니다.

2023-05-18 01:41 UTC, shineMeoseuk commented on src/main/java/kr/cafeIn/cafeorder/service/CafeTableService.java
> +		if (orderMapper.isExistsNowOrderByCafeTableId(cafeTableId)) {
넵 멘토님 수정하도록 하겠습니다~!

2023-06-28 13:43 UTC, f-lab-joseph approved these changes

2023-07-06 12:47 UTC, merged